services:
  app:
    build: .
    ports: 
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy  # Waits for the DB healthcheck to pass
      redis:
        condition: service_started
    # Using sh -c is generally safer across all Linux distributions
    command: sh -c "uv run alembic upgrade head && uv run fastapi run src/ --host 0.0.0.0 --port 8000"
  
  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    healthcheck:
      # Pings PostgreSQL to check if it is ready to accept connections
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  
  worker:
    build: .
    command: uv run celery -A src.celery_tasks.c_app worker --loglevel=info
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

volumes:
  db_data: